### ISSUE TITLE
running ./gradle build in kafka says no such file or directory

### ISSUE THREAD

**Issue by ronnie8778** [airbnb/SpinalTap#17]
Hi there,

I am trying to setup Spinaltap for testing purposes by following the readme, however, after downloaded kafka and I go in to Kafka folder and run ./gradle build, it says **`bash: ./gradle: No such file or directory`**. Do I need to configure anything?

**Comment by mangobatao** [comment]
@ronnie8778 you can follow https://github.com/apache/kafka about how to build Kafka locally.

**Comment by ronnie8778** [comment]
@mangobatao isn't Kafka can run out of the box after I unzip it? Do I still need to run gradle build?

**Comment by mangobatao** [comment]
@ronnie8778 if you download the source code, you need to build and using the script to invoke the jar. You can check whether the jar exists or not while starting by the script.

**Comment by ronnie8778** [comment]
@mangobatao thanks, managed to get it done.
