### ISSUE TITLE
java.lang.NullPointerException: schemaStoreConfig

### ISSUE THREAD

**Issue by ronnie8778** [airbnb/SpinalTap#18]
Hi I am, trying to configure SpinalTap to try on the CDC functionality from mysql to Kafka, I have skipped to configure schema store, do I still need to configure the schema store if I will only use Kafka?

**Comment by mangobatao** [comment]
@ronnie8778 yes, you need to do that. SchemaStore is a required component of this system.

**Comment by ronnie8778** [comment]
@mangobatao Managed to get Spinaltap standalone running, however there is no stream to my Kafka topic, anything I might missed out? My spinaltap standalone config as follow:

zk-connection-string: localhost:2181
zk-namespace: spinaltap-standalone
kafka-config:
  bootstrap_servers: localhost:9092
mysql-user: user
mysql-password: password
mysql-server-id: 1
mysql-schema-store:
    host: localhost
    port: 3306
    database: spinaltap
    archive-database: spinaltap_archive
mysql-sources:
  - name: localhost
    host: localhost
    port: 3306
    host_role: MASTER
    socket_timeout_seconds: -1
    schema_version_enabled: true
    initial_binlog_position:
      fileName: mysql-bin.000001
      position: 1
      nextPosition: 1
    tables:
      - testdb:testcdc

**Comment by mangobatao** [comment]
@ronnie8778 how did you send insert/update/delete to MySQL? What's in your binary log?

**Comment by zuofei** [comment]
@ronnie8778 schema store is not mandatory to run SpinalTap. You can set `schema_version_enabled: false` if you don't need it.

This issue is fixed in #19

**Comment by ronnie8778** [comment]
@zuofei Thanks, let try it out.

**Comment by ronnie8778** [comment]
@mangobatao I use insert command to insert rows to the table. 

I can see the mysqlbinlog contains what I have inserted to my table and other binary code.

**Comment by ronnie8778** [comment]
> @zuofei Thanks, let me try it out.

@zuofei after pulled from git, do I need to rebuild the software? If I run directly, I hit with the same error.

**Comment by ronnie8778** [comment]
> @ronnie8778 Yes, please rebuild the jar by running `./gradlew shadowjar`.
> Please paste the logs so we can look into your issue in your setup.

@zuofei able to start it now, thanks!
